### ISSUE TITLE
Usage documentation?

### ISSUE THREAD

**Issue by GlenKPeterson** [transpect/idmlvalidation#1]
What is the status of this project?  I would like to validate some IDML files.  Command line is fine.  A few lines showing typical usage would be great.  Thanks!

OK, I found the only bash script and git pulled your project.  Where do I find trang.jar?

From `idmlvalidation/schema` directory I did and got:
```
$ ./rnc2rng.sh 
Error: Unable to access jarfile /data/develop/pglatza/trang-20091111/trang.jar
Error: Unable to access jarfile /data/develop/pglatza/trang-20091111/trang.jar
sed: can't read rng//MasterSpreads/*.rng: No such file or directory
Error: Unable to access jarfile /data/develop/pglatza/trang-20091111/trang.jar
sed: can't read rng//Spreads/*.rng: No such file or directory
Error: Unable to access jarfile /data/develop/pglatza/trang-20091111/trang.jar
sed: can't read rng//Stories/*.rng: No such file or directory
Error: Unable to access jarfile /data/develop/pglatza/trang-20091111/trang.jar
sed: can't read rng//XML/*.rng: No such file or directory
Error: Unable to access jarfile /data/develop/pglatza/trang-20091111/trang.jar
sed: can't read rng//Resources/*.rng: No such file or directory
```

**Comment by GlenKPeterson** [comment]
OK, I found the only bash script and git pulled your project.  Where do I find trang.jar?

From `idmlvalidation/schema` directory I did and got:
```
$ ./rnc2rng.sh 
Error: Unable to access jarfile /data/develop/pglatza/trang-20091111/trang.jar
Error: Unable to access jarfile /data/develop/pglatza/trang-20091111/trang.jar
sed: can't read rng//MasterSpreads/*.rng: No such file or directory
Error: Unable to access jarfile /data/develop/pglatza/trang-20091111/trang.jar
sed: can't read rng//Spreads/*.rng: No such file or directory
Error: Unable to access jarfile /data/develop/pglatza/trang-20091111/trang.jar
sed: can't read rng//Stories/*.rng: No such file or directory
Error: Unable to access jarfile /data/develop/pglatza/trang-20091111/trang.jar
sed: can't read rng//XML/*.rng: No such file or directory
Error: Unable to access jarfile /data/develop/pglatza/trang-20091111/trang.jar
sed: can't read rng//Resources/*.rng: No such file or directory
```

**Comment by gimsieke** [comment]
Hi Glen, I think there is some documentation in the readme. It seems to point to our svn server where this lib used to reside. This is just an XProc step that encapsulates Adobe’s Relax NG schemas and gives an [SVRL](http://schematron.com/wp-content/uploads/2016/12/svrl.rnc_.txt) file as a result. This SVRL file is quite verbose. Its validation messages need to be rendered, either as a text or as an HTML report. This HTML report will be generated by another XProc step that renders all Schematron or Relax NG validation messages that accrue during a conversion pipeline into an HTML rendering of the IDML input. The [invocation instructions in the svn repo](https://subversion.le-tex.de/idmltools/trunk/validation_frontend/README.txt) might just give you a hint on how to perform this additional rendering, although I’m afraid that some tweaking might be necessary to make it run as a standalone validation process. The old front end repo will also provide an XProc processor (XML Calabash) by means of an svn external. However, it will not validate against the most recent IDML schemas. 
If you take the XProc library as it is in the present github repo, I’m afraid without XProc and SVRL knowledge, there is currently nothing useful that you can do with this library. This is because we didn’t bother to migrate the front-end repo yet. The library needs to be present here nevertheless, even without frontend and documentation, because we need it as a git submodule or svn external in other projects. 
I cannot tell you a date when we’ll migrate the old Subversion-based front end to a front end that relies on git submodules and also provides a bash/bat script for invocation. This could certainly be accelerated if someone paid for this migration. I think migration itself will take approx. 3 hours. But as I said, this is currently not a priority task unless someone pays us for it.

**Comment by GlenKPeterson** [comment]
OK, thank you for your response.  We were considering using IDML as a format for communication between an online system and InDesign before converting to PDF for printing, but I think (at least for the next few days) we're going to try to go straight to PDF and skip InDesign and IDML altogether.  Depending on how that works out, I may not need to validate IDML after all.  Thank you again!
